CC=g++
CXX=g++
#CXX= clang++
#CPPFLAGS= -std=c++11
#-stdlib=libc++
EXECS= TimerClass SimpleString
OBJECTS= TimerClass.o SimpleString.o
all: $(EXECS) $(OBJECTS)

#%: %.o

#%.o: %.cpp



clean:
	rm $(EXECS) $(OBJECTS)

.PHONY: all clean
